# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thank you for your interest in the Rating System! Remember to express yourself clearly in the issue

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thank you for your interest in the Rating System! Remember to check if you have followed the formatting standards and formatted the code. I heard that Pull Requests that are consistent with the project style are easier to merge

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  congratulations! Your Pull Request has been merged for the first time! :smile:

# It is recommend to include as many gifs and emojis as possible
