name: There is a bug
description: Identify the issues that have arisen
title: "[Bug] "
labels: ["bug", "help wanted"]

body:
  - type: markdown
    attributes:
      value: Welcome to raise new issues for the Rating System! Please fill out the following form
  - type: checkboxes
    id: confirm
    attributes:
      label: Please choose
      options:
        - label: I am working on fixing this bug
          required: false
  - type: input
    id: page
    attributes:
      label: I am currently accessing this feature
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: I found that there is such a bug
    validations:
      required: true
