name: 报告 Bug | Bug Report
description: 汇报一个错误让工作人员处理 | Create a report to help us improve
title: "[BUG]"
labels: ["整叉劈了 | Bug", "需要帮助 | Help Wanted"]

- body:
  - type: textarea
    id: what-happened
    attributes:
      label: 清楚简明地描述这个 bug 是啥。 | A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    id: to-reproduce
    attributes:
      label: 写出重现 Bug 的步骤： | Steps to reproduce the behavior
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: 清楚简明地描述你认为程序应该做的事情。 | A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 如果可以的话，附上屏幕截图来帮助表现 bug。 | If applicable, add screenshots to help explain your problem. 
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 如果，你还有想说的话…… | Add any other context about the problem here. 
    validations:
      required: false
