name: Add new features
description: Apply to add a new feature
title: "[Feature] "
labels: ["enhancement", "help wanted"]

body:
  - type: markdown
    attributes:
      value: Welcome to raise new issues for the Rating System! Please fill out the following form
  - type: textarea
    id: page
    attributes:
      label: The problem I encountered is
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: I hope to have such a solution
    validations:
      required: true
  - type: textarea
    id: alternate
    attributes:
      label: I think these alternative options are also acceptable
    validations:
      required: false
