name: Check Format

on: [push, pull_request]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Setup Node.js 18.20
        with:
          node-version: '18.20'
          check-latest: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          npm install
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format
        run: npm run format

      - name: Check Format
        run: git diff --exit-code
